sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t madhanrajan/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true madhanrajan/docker-react npm run test