sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t madhanrajan/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true madhanrajan/docker-react npm run test

deploy:
    provider: azure_web_apps
    site: https://react-dock.azurewebsites.net
    username: $USERNAME
    password:
        secure: $PASSWORD
    on:
        branch: master
        